on: [push]
jobs:
  test:
    runs-on: nix
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check
        run: |
          pwd
          ls -la .
          nix flake check
