on: [push]
jobs:
  check-format:
    runs-on: nixos-host
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: |
        nix fmt -- --check .
        echo 'formatting check passed'

  build-host:
    needs: flake-check
    runs-on: nixos-host
    strategy:
      max-parallel: 1
      matrix:
        info:
          - host: beefcake
          - host: router
          - host: rascal
          - host: dragon
          - host: foxtrot
          - host: flipflop
          - host: steamdeck
          # - host: pinephone # not needed for every push, only nightly builds
    steps:
    - uses: actions/checkout@v4
    - name: Build host
      run: |
        nix run https://flakehub.com/f/DeterminateSystems/nix/2.32.4 -- --option max-jobs auto --show-trace shell nixpkgs#nixos-rebuild -c nixos-rebuild build --flake .#${{ matrix.info.host }} --accept-flake-config
        echo 'nix command completed successfully'

  build-devshell:
    runs-on: nixos-host
    steps:
    - uses: actions/checkout@v4
    - name: Build default devShell
      run: |
        nix run https://flakehub.com/f/DeterminateSystems/nix/2.32.4 -- --option max-jobs auto develop . --build --accept-flake-config
        echo 'nix command completed successfully'

  build-agent-devshell:
    runs-on: nixos-host
    steps:
    - uses: actions/checkout@v4
    - name: Build default devShell
      run: |
        nix run https://flakehub.com/f/DeterminateSystems/nix/2.32.4 -- --option max-jobs auto develop .#agent --build --accept-flake-config
        echo 'nix command completed successfully'

  flake-check:
    runs-on: nixos-host
    steps:
    - uses: actions/checkout@v4
    - name: Check nix flake
      run: |
        nix run https://flakehub.com/f/DeterminateSystems/nix/2.32.4 -- --option max-jobs auto --show-trace flake check --accept-flake-config
        echo 'nix command completed successfully'
