on: [push]
jobs:
  check-format:
    runs-on: nixos-host
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: |
        nix fmt -- --check .
        echo 'formatting check passed'

  build:
    runs-on: nixos-host
    steps:
    - uses: actions/checkout@v4
    - name: Build all hosts and devshells
      run: |
        nix run https://flakehub.com/f/DeterminateSystems/nix/2.32.4 -- --option max-jobs auto --show-trace build --accept-flake-config \
          .#nixosConfigurations.beefcake.config.system.build.toplevel \
          .#nixosConfigurations.router.config.system.build.toplevel \
          .#nixosConfigurations.rascal.config.system.build.toplevel \
          .#nixosConfigurations.dragon.config.system.build.toplevel \
          .#nixosConfigurations.foxtrot.config.system.build.toplevel \
          .#nixosConfigurations.flipflop.config.system.build.toplevel \
          .#nixosConfigurations.steamdeck.config.system.build.toplevel \
          .#devShells.x86_64-linux.default \
          .#devShells.x86_64-linux.agent
        echo 'all builds completed successfully'

  # flake-check:
  #   runs-on: nixos-host
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Check nix flake
  #     run: |
  #       nix run https://flakehub.com/f/DeterminateSystems/nix/2.32.4 -- --option max-jobs auto --show-trace flake check --accept-flake-config
  #       echo 'nix command completed successfully'
