on: [push]
jobs:
  build-host:
    runs-on: nix-latest
    strategy:
      matrix:
        info:
          - host: beefcake
          - host: router
          - host: dragon
          - host: foxtrot
          - host: flipflop
    steps:
    - uses: actions/checkout@v3
    - name: Build host
      run: |
        nix shell nixpkgs#nixos-rebuild -c nixos-rebuild build --flake .#${{ matrix.info.host }} --accept-flake-config

  build-devshell:
    runs-on: nix-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build default devShell
      run: |
        nix develop . --build --accept-flake-config

  flake-check:
    runs-on: nix-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check nix flake
      run: |
        nix flake check --accept-flake-config
