[colors]
ansi = ["#45475a", "#f38ba8", "#a6e3a1", "#fab387", "#74c7ec", "#cba6f7", "#f9e2af", "#bac2de"]
background = "#1e1e2e"
brights = ["#585b70", "#f38ba8", "#a6e3a1", "#fab387", "#74c7ec", "#cba6f7", "#f9e2af", "#a6adc8"]
compose_cursor = "#fab387"
cursor_bg = "#cdd6f4"
cursor_border = "#cdd6f4"
cursor_fg = "#1e1e2e"
foreground = "#cdd6f4"
scrollbar_thumb = "#181825"
selection_bg = "#f9e2af"
selection_fg = "#1e1e2e"
split = "#585b70"

[colors.tab_bar]
background = "#313244"
[colors.tab_bar.active_tab]
bg_color = "#74c7ec"
fg_color = "#1e1e2e"
italic = false

[colors.tab_bar.inactive_tab]
bg_color = "#181825"
fg_color = "#6c7086"
italic = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#313244"
fg_color = "#74c7ec"
italic = false

[colors.tab_bar.new_tab]
bg_color = "#181825"
fg_color = "#6c7086"
italic = false

[colors.tab_bar.new_tab_hover]
bg_color = "#313244"
fg_color = "#74c7ec"
italic = false
