[aliases]
tug = [
    "bookmark",
    "move",
    "--from",
    "heads(::@- & bookmarks())",
    "--to",
    "@-",
]

[git]
auto-track-bookmarks = true

[remotes.origin]
auto-track-bookmarks = "glob:*"

[revset-aliases]
# Make any change that has been pushed to a remote immutable.
# This prevents accidental rewrites that cause divergent changes.
"immutable_heads()" = "trunk() | remote_bookmarks()"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[templates]
draft_commit_description = """
concat(
  coalesce(description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
"""

[ui]
paginate = "never"

[user]
email = "ci@lyte.dev"
name = "CI"
